# Generated by Django 4.2.7 on 2023-11-20 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbuddy', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Cashbuddy User'},
        ),
    ]
